Upgrade to latest react-native (0.44.x)
oney/RCTWebRTCDemo pull request #52
Opened 2017-05-18 02:36 UTC by philikon

2017-05-18 05:44 UTC, zxcpoiu requested changes
Hi @philikon long time no see

I don't have iOS device to test it now.
have you tested on iOS?

2017-05-18 05:44 UTC, zxcpoiu commented on android/app/src/main/java/com/rctwebrtcdemo/MainApplication.java
> +import com.facebook.soloader.SoLoader;
oops, seems you killed `com.oney.WebRTCModule.WebRTCModulePackage` therefore `cannot find symbol`

2017-05-19 05:37 UTC, philikon commented
Yes, I have tested on iOS. Sorry, I did not test Android before submitting this PR. I'll fix the Android build.

2017-05-19 05:39 UTC, philikon commented
Btw, have you seen https://github.com/oney/react-native-webrtc/issues/274? This app is affected too.

2017-05-19 06:09 UTC, philikon commented
The latest commit appears to be a workaround for https://github.com/oney/react-native-webrtc/issues/274, but the underlying issue is not solved.

2017-05-19 06:44 UTC, zxcpoiu commented
thanks @philikon 

merge this first.
we can continue the discussion in https://github.com/oney/react-native-webrtc/issues/274
I don't have video use case though but folks at jitsi might have some thoughts on it.

2017-05-19 06:44 UTC, zxcpoiu approved these changes

2017-05-19 06:44 UTC, merged